version: '3'
services:
  db:
    image: postgres:10.21-alpine3.16
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: "pgcwip42:"
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
  memcached:
    image: memcached:1.6.21-alpine3.18
    ports:
      - "11211:11211"
  mailserver:
    image: mailhog/mailhog
    ports:
    - "1025:1025"
    - "8025:8025"
  reddit:
    build: .
    volumes:
      - .:/reddit
    ports:
      - "8000:8000"
      - "4005:4005"
    depends_on:
      - db
    tty: true
