version: '3'
services:
  db:
    image: postgres:12.17-alpine3.19
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: "pgcwip42:"
    ports:
      - '5432:5432'
    volumes:
      - ../../tmp/db/test:/var/lib/postgresql/data
      - ../../script/db:/docker-entrypoint-initdb.d
    networks:
      - reddit10_test_nw
networks:
  reddit10_test_nw:
    external: true
